### ISSUE TITLE
[Suggestions] Using publicly available Igor bootstrapper

### ISSUE THREAD

**Issue by shichen85** [OmegaMetor/GameMakerBuildAction#1]
Hello, I am working on something similar and came across these publicly accessible bootstrapper versions of Igor:

https://gms.yoyogames.com/igor_win-x64.zip
https://gms.yoyogames.com/igor_win-arm64.zip
https://gms.yoyogames.com/igor_linux-x64.zip
https://gms.yoyogames.com/igor_linux-arm.zip
https://gms.yoyogames.com/igor_linux-arm64.zip
https://gms.yoyogames.com/igor_osx-x64.zip
https://gms.yoyogames.com/igor_osx.11.0-arm64.zip

You can download them directly if you are interested in not packaging Igor in your action.

**Comment by OmegaMetor** [comment]
Oh nice, i'd asked support about that and they only said that it'd be possible to have that from building igor from source, thank you so much! Yeah, i'll 100% use these instead. Can I ask where you found these too?

**Comment by shichen85** [comment]
Whoops. Totally missed this notification. You are welcome! This was a feature we requested a long time ago and at some point it was released. GameMaker use it too such as in the TestFramework repo: https://github.com/yoyogames/GM-TestFramework/blob/7a51784a277365780f049d029dadc88beedb4b95/framework_launcher.py#L44.

**Comment by shichen85** [comment]
@OmegaMetor Hello, we published these 2 actions for building GMS projects, and I thought you might be interested: https://github.com/bscotch/igor-setup
https://github.com/bscotch/igor-build
